# Generated by Django 5.0.1 on 2024-01-19 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolovlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolov',
            name='izoh',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='QoshimchaTolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(auto_now_add=True)),
                ('summa', models.IntegerField()),
                ('izoh', models.CharField(blank=True, max_length=300)),
                ('tolov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tolovlar.tolov')),
            ],
        ),
    ]
